export enum ResponseMessage {
    SUCCESS = 'SUCCESS',
    FAILED_TO_UPLOAD = 'FAILED_TO_UPLOAD',
    UNAUTHORIZED = 'UNAUTHORIZED',
    COMMENTED = 'COMMENTED',
    SENT_FEEDBACK = 'SENT_FEEDBACK',
    FOLLOWED = 'FOLLOWED',
    NFT_ENCRYPTED = 'NFT_ENCRYPTED',
}
