export enum ResponseMessage {
    SUCCESS = 'SUCCESS',
    FAILED_TO_UPLOAD = 'FAILED_TO_UPLOAD',
    UNAUTHORIZED = 'UNAUTHORIZED',
    COMMENTED = 'COMMENTED',
    SENT_FEEDBACK = 'SENT_FEEDBACK',
    FOLLOWED = 'FOLLOWED',
    NFT_ENCRYPTED = 'NFT_ENCRYPTED',
    ADDED_TO_CART = 'ADDED_TO_CART',
    UPLOADED_TO_CLOUD = 'UPLOADED_TO_CLOUD',
    ACCOUNT_REGISTRATED = 'ACCOUNT_REGISTRATED',
    SERVER_ERROR = 'SERVER_ERROR',
}
